name: 'Bikeclub Paragraph types'
description: 'Provides paragraph types: callout, card, text, and section.'
type: 'Content field'
install:
  - block_content
  - link
  - media
  - options
  - text
  # Contrib.
  - entity_reference_revisions
  - field_group
  - layout_paragraphs
  - paragraphs
  - style_selector
config:
  import:
    paragraphs: '*'
  actions:
    user.role.content_creator:
      createIfNotExists:
        label: 'Content creator'
      grantPermissions:
        - 'create paragraphs_block block content'
        - 'edit any paragraphs_block block content'
    user.role.editor:
      createIfNotExists:
        label: 'Content editor'
      grantPermissions:
        - 'create paragraphs_block block content'
        - 'delete any paragraphs_block block content'
        - 'edit any paragraphs_block block content'
        - 'view any paragraphs_block block content history'
    user.role.site_admin:
      createIfNotExists:
        label: 'Site administrator'
      grantPermissions:
        - 'create paragraphs_block block content'
        - 'delete any paragraphs_block block content'
        - 'edit any paragraphs_block block content'
        - 'view any paragraphs_block block content history'
        
        
